### ISSUE TITLE
关于读取文档的

### ISSUE THREAD

**Issue by wen008** [jingliancui/XamarinFormsTencentX5Sample#1]
读取文档一直有问题  貌似是路径问题~~~有解决办法么~~

**Comment by jingliancui** [comment]
是这个例子运行起来的问题吗？还是？或者你可以将你的问题用一个空项目重现一下压缩上传来看看

**Comment by wen008** [comment]
确实是例子运行起来的问题，貌似你把AndroidManifest.xml里面的
    <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}"
            android:exported="false"
            android:grantUriPermissions="true">
      <meta-data
          android:name="android.support.FILE_PROVIDER_PATHS"
          ***@***.***/provide_file_paths"/>
</provider>
去掉了。
而android.support.v4.content.FileProvider需要nuget安装Xamarin.Android.Support.v4
然后打开文件就正常了~~

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年6月23日 22:59
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [jingliancui/XamarinFormsTencentX5Sample] 关于读取文档的 (#1)


是这个例子运行起来的问题吗？还是？或者你可以将你的问题用一个空项目重现一下压缩上传来看看

―

**Comment by jingliancui** [comment]
ok，这个问题是Android 7及以上版本需要用到的provider，其实不需要引用android.support.v4.content.FileProvider，具体可以参考maui里引用的provider。
